spring:
  application:
    name: AuthorizationServerDemo-02

  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-name: Login me with Google
            client-id:
            client-secret:
          github:
            client-name: Login me with Github
            client-id:
            client-secret:

server:
  port: 8080

logging:
  level:
    org.springframework: INFO